default_email:
    email: baicizhan@gmail.com
    password: a3J0emRmYWhleXpnaHh2dw==\n
    
jiongji:
    email: jiongzai@jiongji.com
    password: c2FudHVpdGU=\n


ex_qq:
    email: service@baicizhan.com
    password: YmN6MTk4OGdvZ29nbw==\n